### ISSUE TITLE
Dodaj .gitignore

### ISSUE THREAD

**Issue by matejm** [SausageCode/Elektrotehnika-UNI-1let#1]
Dodaj `.gitignore` datoteko, v kateri imaš seznam datotek, ki jih nočeš dodati v commit.

Primer `.gitignore` datoteke za [LaTeX](https://github.com/matejm/domace-naloge-analiza/blob/master/.gitignore). Tako datoteko zna GitHub narediti sam, ko narediš nov repository (ni treba dodat vseh končnic). Prav tako notri dodaj mapo `.idea/`, tega se tudi ne commita ([še en primer](https://github.com/electronpass/electronpass-desktop/blob/develop/.gitignore)). 

Pa še koristno se je naučit uporabljat issue-je :)

**Comment by prtzl** [comment]
Hvala. Bom zrihtal kar se da hitro :)
